/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface IdentifyGroupRequestBody {
    /** <span style="white-space: nowrap">`non-empty`</span> */
    identifier: string;
    properties: Record<string, unknown>;
}
