/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import * as DoptApi from "../../../../api";
import * as core from "../../../../core";

export const Request: core.serialization.Schema<
    serializers.users.identifyUsers.Request.Raw,
    DoptApi.IdentifyBatchRequestBodyItem[]
> = core.serialization.list(
    core.serialization.lazyObject(async () => (await import("../../..")).IdentifyBatchRequestBodyItem)
);

export declare namespace Request {
    type Raw = serializers.IdentifyBatchRequestBodyItem.Raw[];
}
