/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as errors from "../../errors";
import * as DoptApi from "..";

export class BadRequestError extends errors.DoptApiError {
    constructor(body: DoptApi.BadRequestErrorResponseBody) {
        super({
            statusCode: 400,
            body: body,
        });
        Object.setPrototypeOf(this, BadRequestError.prototype);
    }
}
