/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as errors from "../../errors";
import * as DoptApi from "..";

export class InternalServerError extends errors.DoptApiError {
    constructor(body: DoptApi.InternalServerErrorResponseBody) {
        super({
            statusCode: 500,
            body: body,
        });
        Object.setPrototypeOf(this, InternalServerError.prototype);
    }
}
