/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as errors from "../../errors";
import * as DoptApi from "..";

export class UnauthorizedError extends errors.DoptApiError {
    constructor(body: DoptApi.UnauthorizedErrorResponseBody) {
        super({
            statusCode: 401,
            body: body,
        });
        Object.setPrototypeOf(this, UnauthorizedError.prototype);
    }
}
