/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type BadRequestErrorResponseBodyCode = "invalid_request_error" | "intent_request_error";

export const BadRequestErrorResponseBodyCode = {
    InvalidRequestError: "invalid_request_error",
    IntentRequestError: "intent_request_error",
} as const;
