/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as DoptApi from "..";

export type IdentifySegmentRequestBody =
    | DoptApi.IdentifySegmentRequestBodyIdentifySegmentRequestBody
    | DoptApi.IdentifySegmentRequestBodyIdentifySegmentRequestBody;
