/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface IdentifySegmentRequestBodyGroup {
    groupId: string;
    userId: string;
    traits: Record<string, unknown>;
}
