/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface SegmentGroup {
    type: "group";
    groupId: string;
    userId: string;
    traits: Record<string, unknown>;
}
