/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface SegmentGroup {
    type: "group";
    /** <span style="white-space: nowrap">`non-empty`</span> */
    groupId: string;
    /** <span style="white-space: nowrap">`non-empty`</span> */
    userId: string;
    traits: Record<string, unknown>;
}
