/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface SegmentCommon {
    /** <span style="white-space: nowrap">`non-empty`</span> */
    userId: string;
    traits: Record<string, unknown>;
}
