/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as DoptApi from "../../api";
import * as core from "../../core";

export const BadRequestErrorResponseBody: core.serialization.ObjectSchema<
    serializers.BadRequestErrorResponseBody.Raw,
    DoptApi.BadRequestErrorResponseBody
> = core.serialization.object({
    code: core.serialization.lazy(async () => (await import("..")).BadRequestErrorResponseBodyCode),
    details: core.serialization.string(),
});

export declare namespace BadRequestErrorResponseBody {
    interface Raw {
        code: serializers.BadRequestErrorResponseBodyCode.Raw;
        details: string;
    }
}
