/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as DoptApi from "../../api";
import * as core from "../../core";

export const IdentifySegmentRequestBodyIdentify: core.serialization.ObjectSchema<
    serializers.IdentifySegmentRequestBodyIdentify.Raw,
    DoptApi.IdentifySegmentRequestBodyIdentify
> = core.serialization.object({
    userId: core.serialization.string(),
    traits: core.serialization.record(core.serialization.string(), core.serialization.unknown()),
});

export declare namespace IdentifySegmentRequestBodyIdentify {
    interface Raw {
        userId: string;
        traits: Record<string, unknown>;
    }
}
