/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as DoptApi from "../../api";
import * as core from "../../core";

export const IdentifyBatchResponseBody: core.serialization.ObjectSchema<
    serializers.IdentifyBatchResponseBody.Raw,
    DoptApi.IdentifyBatchResponseBody
> = core.serialization.object({
    count: core.serialization.number(),
});

export declare namespace IdentifyBatchResponseBody {
    interface Raw {
        count: number;
    }
}
