/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as DoptApi from "../../api";
import * as core from "../../core";

export const IdentifyRequestBody: core.serialization.Schema<
    serializers.IdentifyRequestBody.Raw,
    DoptApi.IdentifyRequestBody
> = core.serialization.record(core.serialization.string(), core.serialization.unknown());

export declare namespace IdentifyRequestBody {
    type Raw = Record<string, unknown>;
}
