/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as DoptApi from "../../api";
import * as core from "../../core";

export const IdentifyBatchRequestBody: core.serialization.Schema<
    serializers.IdentifyBatchRequestBody.Raw,
    DoptApi.IdentifyBatchRequestBody
> = core.serialization.list(
    core.serialization.lazyObject(async () => (await import("..")).IdentifyBatchRequestBodyItem)
);

export declare namespace IdentifyBatchRequestBody {
    type Raw = serializers.IdentifyBatchRequestBodyItem.Raw[];
}
