/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as DoptApi from "../../api";
import * as core from "../../core";

export const IdentifyBatchRequestBodyItemGroupsItem: core.serialization.ObjectSchema<
    serializers.IdentifyBatchRequestBodyItemGroupsItem.Raw,
    DoptApi.IdentifyBatchRequestBodyItemGroupsItem
> = core.serialization.object({
    identifier: core.serialization.string(),
    properties: core.serialization.record(core.serialization.string(), core.serialization.unknown()),
});

export declare namespace IdentifyBatchRequestBodyItemGroupsItem {
    interface Raw {
        identifier: string;
        properties: Record<string, unknown>;
    }
}
