/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as DoptApi from "../../api";
import * as core from "../../core";

export const IdentifyRequestParams: core.serialization.ObjectSchema<
    serializers.IdentifyRequestParams.Raw,
    DoptApi.IdentifyRequestParams
> = core.serialization.object({
    identifier: core.serialization.string(),
});

export declare namespace IdentifyRequestParams {
    interface Raw {
        identifier: string;
    }
}
