/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as DoptApi from "../../api";
import * as core from "../../core";

export const IdentifyBatchRequestBodyItem: core.serialization.ObjectSchema<
    serializers.IdentifyBatchRequestBodyItem.Raw,
    DoptApi.IdentifyBatchRequestBodyItem
> = core.serialization.object({
    identifier: core.serialization.string(),
    properties: core.serialization.record(core.serialization.string(), core.serialization.unknown()),
    groups: core.serialization
        .list(core.serialization.lazyObject(async () => (await import("..")).IdentifyBatchRequestBodyItemGroupsItem))
        .optional(),
});

export declare namespace IdentifyBatchRequestBodyItem {
    interface Raw {
        identifier: string;
        properties: Record<string, unknown>;
        groups?: serializers.IdentifyBatchRequestBodyItemGroupsItem.Raw[] | null;
    }
}
