/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as DoptApi from "../../api";
import * as core from "../../core";

export const IdentifySegmentRequestBody: core.serialization.Schema<
    serializers.IdentifySegmentRequestBody.Raw,
    DoptApi.IdentifySegmentRequestBody
> = core.serialization
    .union("type", {
        identify: core.serialization.lazyObject(async () => (await import("..")).IdentifySegmentRequestBodyIdentify),
        group: core.serialization.lazyObject(async () => (await import("..")).IdentifySegmentRequestBodyGroup),
    })
    .transform<DoptApi.IdentifySegmentRequestBody>({
        transform: (value) => value,
        untransform: (value) => value,
    });

export declare namespace IdentifySegmentRequestBody {
    type Raw = IdentifySegmentRequestBody.Identify | IdentifySegmentRequestBody.Group;

    interface Identify extends serializers.IdentifySegmentRequestBodyIdentify.Raw {
        type: "identify";
    }

    interface Group extends serializers.IdentifySegmentRequestBodyGroup.Raw {
        type: "group";
    }
}
