/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as DoptApi from "../../api";
import * as core from "../../core";

export const IdentifySegmentRequestBody: core.serialization.Schema<
    serializers.IdentifySegmentRequestBody.Raw,
    DoptApi.IdentifySegmentRequestBody
> = core.serialization.undiscriminatedUnion([
    core.serialization.lazyObject(
        async () => (await import("..")).IdentifySegmentRequestBodyIdentifySegmentRequestBody
    ),
    core.serialization.lazyObject(
        async () => (await import("..")).IdentifySegmentRequestBodyIdentifySegmentRequestBody
    ),
]);

export declare namespace IdentifySegmentRequestBody {
    type Raw =
        | serializers.IdentifySegmentRequestBodyIdentifySegmentRequestBody.Raw
        | serializers.IdentifySegmentRequestBodyIdentifySegmentRequestBody.Raw;
}
