/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as DoptApi from "../../api";
import * as core from "../../core";

export const NotFoundErrorResponseBody: core.serialization.ObjectSchema<
    serializers.NotFoundErrorResponseBody.Raw,
    DoptApi.NotFoundErrorResponseBody
> = core.serialization.object({
    code: core.serialization.stringLiteral("not_found_error"),
    details: core.serialization.string(),
});

export declare namespace NotFoundErrorResponseBody {
    interface Raw {
        code: "not_found_error";
        details: string;
    }
}
