/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as DoptApi from "../../api";
import * as core from "../../core";

export const UnauthorizedErrorResponseBody: core.serialization.ObjectSchema<
    serializers.UnauthorizedErrorResponseBody.Raw,
    DoptApi.UnauthorizedErrorResponseBody
> = core.serialization.object({
    code: core.serialization.stringLiteral("unauthorized_error"),
    details: core.serialization.string(),
});

export declare namespace UnauthorizedErrorResponseBody {
    interface Raw {
        code: "unauthorized_error";
        details: string;
    }
}
