/**
 * This file was auto-generated by Fern from our API Definition.
 */

export const DoptApiEnvironment = {
    Default: "https://users.dopt.com",
} as const;

export type DoptApiEnvironment = typeof DoptApiEnvironment.Default;
