/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as DoptApi from "../../../..";

export interface IdentifyUserRequestBody {
    /** <span style="white-space: nowrap">`non-empty`</span> */
    identifier: string;
    properties: Record<string, unknown>;
    groups?: DoptApi.IdentifyUserRequestBodyGroupsItem[];
}
